version: "3"
services:

  springbootjpa:
    image: docker-spring-boot
    build: .
    ports:
      - "9088:9088"
    networks:
      - products-mysql
    depends_on:
      mysqldb:
        condition: service_healthy

  mysqldb:
    image: mysql:8
    networks:
      - products-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bootdb
    ports:
      - "3306:3306"
    volumes:
      - ./mysqldata:/var/lib/mysql
    healthcheck:
            test: ["CMD", "mysqladmin", "-uroot", "-p$$MYSQL_ROOT_PASSWORD" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10

networks:
  products-mysql: